# project information
site_name: XIAOYUE'S NOTES

# Configuration
theme:
  name: 'material'
  palette:
    primary: 'purple'
    accent: 'pink'
  feature:
    tabs: false

# Plugins
plugins:
  - mknotebooks


markdown_extensions:
  - codehilite:
      guess_lang: false
  - meta
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Notes: notes.md

extra:
  social:
    - type: 'github'
      link: 'https://github.com/MaxineXiaoyueMa/ds-notes'
